name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from Git
        uses: actions/checkout@v3

      - name: Set up JDK (for SonarQube)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # - name: Install SonarQube Scanner
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y sonar-scanner

      # - name: SonarQube Analysis
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     sonar-scanner -Dsonar.projectKey=jen-son-doc -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      #     echo "Successfully Scanned Vulnerabilities"

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker --version
          docker build -t fewebsite .
          docker run -d -p 8085:80 --name=onixwebsite fewebsite

